spring:
  application:
    name: challenge
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
      format_sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: 'jdbc:mysql:///challengedb'
    username: testuser
    password: testpassword
